### ISSUE TITLE
Shadowserver problem

### ISSUE THREAD

**Issue by eldryoth** [AbuseIO/abuseio-docker#5]
Hi! :)

We have been trying to get AbuseIO to work we mainly would like to test out the Shadowserver reports with this tool.

I am afraid I am probably missing something with the installation or configuration because whatever we try we cannot get it to work, just to clarify we can access AbuseIO fine the graphical interface what we cannot get to work is the shadowserver parsing.

Could someone have a look at all the step we do below and tell me what I miss? I just write all steps we do just to give a clear picture.

OS Used: Debian 9

Commands run:
**update OS:**
```
apt-get update && apt-get upgrade
apt-get dist-upgrade
```

**Add nginx as proxy to AbuseIO docker container:**
```
apt install curl gnupg2 ca-certificates lsb-release
echo "deb http://nginx.org/packages/mainline/debian `lsb_release -cs` nginx"     | sudo tee /etc/apt/sources.list.d/nginx.list
curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
sudo apt-key fingerprint ABF5BD827BD9BF62
apt update
apt install nginx
systemctl enable nginx.service
systemctl start nginx.service
(copy config to proxy etc)
```

**Allow port 80 and 443 in firewall:**
```
iptables -A INPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables-save > /etc/iptables.conf
```

**Get certificate for domain AbuseIO will run under:**
```
apt install python3-certbot-dns-route53
apt install certbot
apt install python3-pip
pip3 install certbot-dns-route53
certbot certonly --dns-route53 -d abuseio.example.com
```

**Install Docker from official repository:**
```
apt-get install     apt-transport-https     ca-certificates     curl     gnupg2     software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io
systemctl start docker.service
systemctl enable docker.service
```

**Create AbuseIO local directories:**
```
mkdir -p /var/log/abuseio
mkdir -p /srv/abuseio/config
mkdir -p /srv/abuseio/data
```

**Start AbuseIO container:**
```
docker run -d -p 8000:8000 -p 3306:3306 -e "APP_URL=https://abuseio.example.com" -v /srv/abuseio/config:/config -v /srv/abuseio/data:/data -v /var/log/abuseio:/log abuseio/abuseio:latest
```
I did go with "latest" here because when I used "4.1" it doesn't do anything at all and log will show me no information, it only says "Starting fetchmail 6.3.26 daemon". (so the error below is based on 4.2)

**Add email configuration:**
```
nano /srv/abuseio/config/fetchmailrc
```

**(we add this)**
```
# set username
set postmaster "abuseio"
# set polling time (5 minutes)
set daemon 30

# Read BF abuseio email
poll imap.mail.eu-west-1.awsapps.com with proto imap
  user 'abuse@example.com' there with password '*XXX' is abuseio here options ssl
mda "/usr/bin/procmail -m /etc/procmailrc"
```

But this not work we always end up with errors like:

> Oct 17 09:45:13 83cac2cb4966 fetchmail[3518]: 1 message for abuse@example.com at imap.mail.eu-west-1.awsapps.com.
> Oct 17 09:45:13 83cac2cb4966 fetchmail[3518]: reading message abuse@example.com@imap.mail.eu-west-1.awsapps.com:1 of 1 (4063 header octets) (3540 body octets) (log message incomplete)
> Oct 17 09:45:13 83cac2cb4966 fetchmail[3518]: Error writing to MDA: Broken pipe

Does anyone see from this what we do wrong?

**Comment by eldryoth** [comment]
So I did go back to 4.1, to investigate little more and I now found an error so what works is:

I receive email from Shadowserver on my email and I can see AbuseIO finds the email tries to process it and deletes it from my mailbox.

But then it gives this error:
```
Oct 18 13:52:46 c17ada65a609 abuseio[664]: production.INFO: AbuseIO\Console\Commands\Receive\EmailCommand: Being called upon to receive an incoming e-mail
Oct 18 13:52:46 c17ada65a609 abuseio[664]: production.INFO: AbuseIO\Console\Commands\Receive\EmailCommand: Pushing incoming email into queue file: mailarchive/20191018/803a3ccb-d2e8-4a2f-ad24-bcc00ad99604.eml
Oct 18 13:52:46 c17ada65a609 abuseio[664]: production.INFO: AbuseIO\Console\Commands\Receive\EmailCommand: Successfully received the incoming e-mail
Oct 18 13:52:49 c17ada65a609 abuseio[606]: production.INFO: AbuseIO\Jobs\EmailProcess: Queued worker is starting the processing of email file: mailarchive/20191018/803a3ccb-d2e8-4a2f-ad24-bcc00ad99604.eml
Oct 18 13:52:49 c17ada65a609 abuseio[606]: production.ERROR: AbuseIO\Jobs\EmailProcess: : No parser available to handle message from : Shadowserver <autoreports@shadowserver.org> with subject: [XXX] Shadowserver XXX Open LDAP (TCP) Services Report: 2019-10-16
Oct 18 13:52:49 c17ada65a609 abuseio[606]: production.ERROR: AbuseIO\Jobs\EmailProcess: Email processor ending with errors. The received e-mail will be bounced to the admin for investigation
Oct 18 13:52:49 c17ada65a609 abuseio[606]: production.ERROR: Swift_TransportException: Connection could not be established with host localhost [Cannot assign requested address #99] in /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:277 Stack trace: #0 /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection() #1 /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array) #2 /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(394): Swift_Mailer->send(Object(Swift_Message), Array) #4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(179): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message)) #5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(133): Illuminate\Mail\Mailer->send(NULL, Array, Object(Closure)) #6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Mail\Mailer->raw('AbuseIO was not...', Object(Closure)) #7 /opt/abuseio/app/Jobs/AlertAdmin.php(48): Illuminate\Support\Facades\Facade::__callStatic('raw', Array) #8 /opt/abuseio/app/Jobs/EmailProcess.php(279): AbuseIO\Jobs\AlertAdmin::send('AbuseIO was not...', Array) #9 /opt/abuseio/app/Jobs/EmailProcess.php(175): AbuseIO\Jobs\EmailProcess->exception() #10 [internal function]: AbuseIO\Jobs\EmailProcess->handle() #11 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(192): Illuminate\Container\Container->call(Array) #13 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(AbuseIO\Jobs\EmailProcess)) #14 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(AbuseIO\Jobs\EmailProcess)) #15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(AbuseIO\Jobs\EmailProcess)) #16 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(AbuseIO\Jobs\EmailProcess)) #17 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(204): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(AbuseIO\Jobs\EmailProcess), Object(Closure)) #19 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array) #20 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array) #21 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(218): Illuminate\Queue\Jobs\DatabaseJob->fire() #22 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '1', '0') #23 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, 'abuseio_email_i...', '0', '3', '1') #24 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(86): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, 'abuseio_email_i...', '0', '3', '1') #25 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon(NULL, 'abuseio_email_i...', '0', '256', '3', '1') #26 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'abuseio_email_i...', '0', '256', true) #27 [internal function]: Illuminate\Queue\Console\WorkCommand->fire() #28 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #29 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array) #30 /opt/abuseio/vendor/symfony/console/Command/Command.php(238): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #31 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #32 /opt/abuseio/vendor/symfony/console/Application.php(840): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #33 /opt/abuseio/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #34 /opt/abuseio/vendor/symfony/console/Application.php(114): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #35 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #36 /opt/abuseio/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #37 {main}
Oct 18 13:52:52 c17ada65a609 abuseio[606]: production.ERROR: AbuseIO\Jobs\EmailProcess: Unexpected exception was raised from the framework. This usually indicates an error within the framework code. A full trace can be found in the logs and should be reported to the developers
Oct 18 13:52:52 c17ada65a609 abuseio[606]: production.ERROR: AbuseIO\Jobs\EmailProcess: Email processor ending with errors. The received e-mail will be bounced to the admin for investigation
Oct 18 13:52:52 c17ada65a609 abuseio[606]: production.ERROR: Swift_TransportException: Connection could not be established with host localhost [Cannot assign requested address #99] in /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:277 Stack trace: #0 /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection() #1 /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array) #2 /opt/abuseio/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(394): Swift_Mailer->send(Object(Swift_Message), Array) #4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(179): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message)) #5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(133): Illuminate\Mail\Mailer->send(NULL, Array, Object(Closure)) #6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Mail\Mailer->raw('AbuseIO was not...', Object(Closure)) #7 /opt/abuseio/app/Jobs/AlertAdmin.php(48): Illuminate\Support\Facades\Facade::__callStatic('raw', Array) #8 /opt/abuseio/app/Jobs/EmailProcess.php(279): AbuseIO\Jobs\AlertAdmin::send('AbuseIO was not...', Array) #9 /opt/abuseio/app/Jobs/EmailProcess.php(72): AbuseIO\Jobs\EmailProcess->exception() #10 [internal function]: AbuseIO\Jobs\EmailProcess->failed(Object(AbuseIO\Jobs\EmailProcess)) #11 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(77): call_user_func(Array, Object(AbuseIO\Jobs\EmailProcess)) #12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(212): Illuminate\Queue\CallQueuedHandler->failed(Array) #13 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(271): Illuminate\Queue\Jobs\Job->failed() #14 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(211): Illuminate\Queue\Worker->logFailedJob('database', Object(Illuminate\Queue\Jobs\DatabaseJob)) #15 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '1', '0') #16 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, 'abuseio_email_i...', '0', '3', '1') #17 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(86): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, 'abuseio_email_i...', '0', '3', '1') #18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon(NULL, 'abuseio_email_i...', '0', '256', '3', '1') #19 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'abuseio_email_i...', '0', '256', true) #20 [internal function]: Illuminate\Queue\Console\WorkCommand->fire() #21 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #22 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array) #23 /opt/abuseio/vendor/symfony/console/Command/Command.php(238): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #24 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #25 /opt/abuseio/vendor/symfony/console/Application.php(840): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #26 /opt/abuseio/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #27 /opt/abuseio/vendor/symfony/console/Application.php(114): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #28 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #29 /opt/abuseio/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #30 {main}
```

**Comment by kruisdraad** [comment]
an update was giving to parser-shadowserver that should resolve the issue.

**Comment by eldryoth** [comment]
> 
> 
> an update was giving to parser-shadowserver that should resolve the issue.

Thank you! :)
