### ISSUE TITLE
No parser available error

### ISSUE THREAD

**Issue by andrewmgee** [AbuseIO/abuseio-docker#9]
We seem to be having an issue with all parsers in the official abuseio/abuseio:4.1 docker container. It errors out with the below:

```
Feb 14 00:29:17 a0b8f175dc1f abuseio[99]: production.INFO: AbuseIO\Console\Commands\Receive\EmailCommand: Being called upon to receive an incoming e-mail
Feb 14 00:29:17 a0b8f175dc1f abuseio[99]: production.INFO: AbuseIO\Console\Commands\Receive\EmailCommand: Pushing incoming email into queue file: mailarchive/20210213/e282c6f1-85f1-4efd-aa05-368fdbdb5593.eml
Feb 14 00:29:17 a0b8f175dc1f abuseio[99]: production.INFO: AbuseIO\Console\Commands\Receive\EmailCommand: Successfully received the incoming e-mail
Feb 14 00:29:20 a0b8f175dc1f abuseio[13]: production.INFO: AbuseIO\Jobs\EmailProcess: Queued worker is starting the processing of email file: mailarchive/20210213/e282c6f1-85f1-4efd-aa05-368fdbdb5593.eml
Feb 14 00:29:20 a0b8f175dc1f abuseio[13]: production.ERROR: AbuseIO\Jobs\EmailProcess: : No parser available to handle message from : Vobile Compliance <p2p@viacomcbs.copyright-notice.com> with subject: Notice of Claimed Infringement - Case ID 123456
Feb 14 00:29:20 a0b8f175dc1f abuseio[13]: production.ERROR: AbuseIO\Jobs\EmailProcess: Email processor ending with errors. The received e-mail will be bounced to the admin for investigation
Feb 14 00:29:20 a0b8f175dc1f abuseio[13]: production.INFO: AlertAdmin: Successfully send out alert to admin admin@isp.local

```

I believe the above example the sender email matches with the `parser-copyrightcompliance` . We've double checked it is in the './vendor/abuseio/parser-*/’, and have also put a copy in the production/parsers folder. But it always gives the above error. Any suggestions?

Not sure if it is related, the only other log entries is the below error
```
Feb 14 00:19:16 a0b8f175dc1f abuseio[14]: production.ERROR: PDOException: SQLSTATE[HY000] [2002] No such file or directory in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55 Stack trace: #0 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=loca...', 'root', 'abuseio', Array) #1 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array) #2 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array) #3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array) #4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(175): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql') #5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('mysql') #6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Connectors/DatabaseConnector.php(38): Illuminate\Database\DatabaseManager->connection('mysql') #7 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(133): Illuminate\Queue\Connectors\DatabaseConnector->connect(Array) #8 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(113): Illuminate\Queue\QueueManager->resolve('database') #9 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(150): Illuminate\Queue\QueueManager->connection('database') #10 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, 'abuseio_delegat...', '30', '3', '5') #11 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(86): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, 'abuseio_delegat...', '30', '3', '5') #12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon(NULL, 'abuseio_delegat...', '30', '256', '3', '5') #13 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'abuseio_delegat...', '30', '256', true) #14 [internal function]: Illuminate\Queue\Console\WorkCommand->fire() #15 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #16 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array) #17 /opt/abuseio/vendor/symfony/console/Command/Command.php(238): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 /opt/abuseio/vendor/symfony/console/Application.php(840): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 /opt/abuseio/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #21 /opt/abuseio/vendor/symfony/console/Application.php(114): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #22 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #23 /opt/abuseio/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #24 {main}
```

In addition the "Exception notification" email it does send out to admin email, with the "failed_message.eml" is always just blank. However the copy of the email stored in mailarchive directory does correctly show the email.

**Comment by kruisdraad** [comment]
At this time we do not expect a new 5.0 build for docker. We have provided an Ansible script to install systems instead.
